spring.application.name=BE
server.port=8080

# Cấu hình kết nối TiKV (Viết trên 1 dòng đơn)
tikv.pd.endpoints=10.19.193.19:2379

# Cấu hình Jackson
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss'Z'
spring.jackson.time-zone=UTC